# Generated by Django 4.0.4 on 2022-06-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='img',
            field=models.CharField(default='./images/default.jpg', max_length=400),
        ),
    ]
