# Generated by Django 4.0.4 on 2022-06-02 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_coin_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.TextField(max_length=150)),
                ('statement', models.TextField(max_length=600)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.coin')),
            ],
        ),
    ]
